name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
oidc:
  client:
    id: "loginapp"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirect_url: "https://127.0.0.1:5555/callback"
  issuer:
    root_ca: "/ssl/ca.pem"
    url: "https://dex.example.com:5556"
  extra_scopes:
    - groups
  offline_as_scope: true
  cross_clients:
  - web
tls:
  enabled: true
  cert: /ssl/cert.pem
  key: /ssl/key.pem
log:
  level: Debug
  format: json
web_output:
  main_client_id: titi
