name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
oidc:
  client:
    id: "loginapp"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirect_url: "http://127.0.0.1:5555/callback"
  issuer:
    root_ca: "example/ssl/ca.pem"
    url: "https://dex.example.com:5556"
