name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
oidc:
  client:
    id: "loginapp"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirect_url: "https://127.0.0.1:5555/callback"
  issuer:
    root_ca: "example/ssl/ca.pem"
    url: "https://dex.example.com:5556"
  extra_scopes:
    - groups
  offline_as_scope: true
  cross_clients:
  - web
tls:
  enabled: true
  cert: example/ssl/cert.pem
  key: example/ssl/key.pem
log:
  level: Debug
  format: json
web_output:
  main_client_id: "loginapp"
  main_username_claim: "email"
  assets_dir: "./assets/"
  skip_main_page: false
clusters:
  - name: myfakecluster
    server: https://myfakecluster.org
    certificate-authority: |
      -----BEGIN CERTIFICATE-----
      MIIC/zCCAeegAwIBAgIULkYvGJPRl50tMoVE4BNM0laRQncwDQYJKoZIhvcNAQEL
      BQAwDzENMAsGA1UEAwwEbXljYTAeFw0xOTAyMTgyMjA5NTJaFw0xOTAyMjgyMjA5
      NTJaMA8xDTALBgNVBAMMBG15Y2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      -----END CERTIFICATE-----
    insecure-skip-tls-verify: false
