apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: loginapp
build:
  artifacts:
  - image: quay.io/fydrah/loginapp
deploy:
  kubectl:
    manifests:
    - test/kubernetes/generated/dex-certs.yaml
    - test/kubernetes/generated/dex-config.yaml
    - test/kubernetes/dex.yaml
    - test/kubernetes/generated/loginapp-certs.yaml
    - test/kubernetes/generated/loginapp-config.yaml
    - test/kubernetes/loginapp.yaml
