{{- if and .Values.config.tls.enabled (not .Values.config.tls.secretName) }}
{{- $altnames := concat (list (include "loginapp.fullname" .) (print (include "loginapp.fullname" .) "." .Release.Namespace ".svc")) .Values.config.tls.altnames }}
{{- $cert := genSelfSignedCert (include "loginapp.fullname" .) .Values.config.tls.altIPs $altnames 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loginapp.fullname" . }}-certs
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}