{{- $config := fromYaml (include "loginapp.configuration" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loginapp.fullname" . }}
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml (mergeOverwrite $config .Values.configOverwrites) | nindent 4 }}
---
{{- if .Values.templates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loginapp.fullname" . }}-templates
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.templates }}
{{ $key | indent 2 }}: |-
{{ $val | nindent 4 }}
{{- end }}
{{- end }}