{{- $config := fromYaml (include "loginapp.configuration" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loginapp.fullname" . }}
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml (mergeOverwrite $config .Values.configOverwrites) | nindent 4 }}
---
{{- if and .Values.templates.error .Values.templates.token}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loginapp.fullname" . }}-templates
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
data:
  error.html: {{ .Values.templates.error }}
  token.html: {{ .Values.templates.token }}
{{- end }}