apiVersion: v1
kind: Service
metadata:
  name: {{ include "loginapp.fullname" . }}
  labels:
    {{- include "loginapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "loginapp.selectorLabels" . | nindent 4 }}
